version: '3.8'
services:
  composer:
    image: composer
    working_dir: /app
    volumes:
      - .:/app

  tests_unit:
    image: php:7.4-cli
    volumes:
      - .:/app
    working_dir: /app
    entrypoint: vendor/bin/phpunit --testsuite=Unit

  tests_feature:
    image: php:7.4-cli
    volumes:
      - .:/app
    working_dir: /app
    entrypoint: vendor/bin/phpunit --testsuite=Feature
