version: '3'
services:

  app:
    image: php:7.4-fpm
    container_name: tickr-schedule-app
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - tickr-schedule-network

  webserver:
    image: nginx:alpine
    container_name: tickr-schedule-webserver
    volumes:
      - ./:/var/www
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/sites:/etc/nginx/sites-available
    ports:
      - "8060:80"
    networks:
      - tickr-schedule-network

networks:
  tickr-schedule-network:
    driver: bridge

volumes:
  dbdata:
    driver: local
